### ISSUE TITLE
编译环境怎么弄,Linux

### ISSUE THREAD

**Issue by PlexPt** [shadowsocksr/shadowsocksr-android#143]
试了好久都编译不过,报错

 sbt native-build clean androipackage-release
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[info] Loading project definition from /home/pt/project/shadowsocksr-android-master/project
[info] Set current project to shadowsocksr (in build file:/home/pt/project/shadowsocksr-android-master/)
[info] ~/project/shadowsocksr-android-master/src/main ~/project/shadowsocksr-android-master
[error] jni/Android.mk:554: jni/openssl/crypto/Android.mk: 没有那个文件或目录
[error] jni/Android.mk:554: jni/openssl/ssl/Android.mk: 没有那个文件或目录
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium    
[info] Android NDK:   shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2-impl.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse41.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-round.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_add.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_madd.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_msub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_sub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow22523.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow225521.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sc.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sqrtm1.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/curve25519_ref10.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h    
[error] jni/Android.mk:554: jni/openssl/crypto/Android.mk: 没有那个文件或目录
[error] jni/Android.mk:554: jni/openssl/ssl/Android.mk: 没有那个文件或目录
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium    
[info] Android NDK:   shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2-impl.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse41.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-round.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_add.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_madd.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_msub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_sub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow22523.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow225521.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sc.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sqrtm1.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/curve25519_ref10.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h    
[error] make: *** No rule to make target 'jni/openssl/ssl/Android.mk'。 停止。
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $55d5d6c1a13a8cf7ebd6$$anonfun$$sbtdef$1.apply(/home/pt/project/shadowsocksr-android-master/build.sbt:76)
	at $55d5d6c1a13a8cf7ebd6$$anonfun$$sbtdef$1.apply(/home/pt/project/shadowsocksr-android-master/build.sbt:72)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:nativeBuild) Native build script exit code: 255
[error] Total time: 0 s, completed 2017-5-8 16:21:43

**Comment by adminlinzi** [comment]
楼主，如果你是debian系列的，可以便捷安装。
```
sudo apt-get install python-pip
sudo pip install shadowsocks
sslocal -s 服务端IP -p 服务端端口号  -l 本地端口号-k "密码" -t 连接延时 -m 加密方式
```
设置浏览器代理到本地指定端口号即可。

**Comment by WarmColor** [comment]
之前3.7版本的时候编译过，最近编译也会报错，编译出来的用不了，看信息猜测是从ss的分支下载jni模块的时候找不到，但是不懂怎么解决
